apiVersion: v1
kind: Service
metadata:
  name: bdlpoc
spec:
  selector:
    app: bdlpoc
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdlpoc
spec:
  selector:
    matchLabels:
      app: bdlpoc
  replicas: 5
  template:
    metadata:
      labels:
        app: bdlpoc
    spec:
      containers:
      - name: bdlpoc
        image: bdlpoc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000